### ISSUE TITLE
Resistor Values

### ISSUE THREAD

**Issue by chengkiang** [achilikin/cdtea#1]
What are the resistor values?

**Comment by achilikin** [comment]
For resistors on the right side of the schematics you can use 10K for all resistors connected to Vcc and 1K for all resistors connected to IO pins.
I used 1k resistor for L293D, connected to EN pins, but it is not needed, you can connect EN pins directly to Vcc.
Resistor for LED is want ever there on CD PCB itself.

Regards,
Andrey
