### ISSUE TITLE
Help with the Diagram

### ISSUE THREAD

**Issue by NickMatthews-1** [achilikin/cdtea#3]
Hello

Im not much of a diagram I am more look at whats there and do it hoping nothing will go wrong. I have all the things I need lying about so if at all possible could you post a picture of the breadboard and name all of the components that would be much appreciated. 

Yours sincerely

Nmatt1

**Comment by Mikajvd** [comment]
i have got the same problem!

**Comment by achilikin** [comment]
Added a picture with wires connected to the motor board of the CD drive used.
